# Credits

This is heavily based on https://github.com/pytorch/tutorials


# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used.

PyTorch a Python based scientific computing package targeted at two sets of
audiences:

- A replacement for numpy to use the power of GPUs
- a deep learning research platform that provides maximum flexibility and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.


In [1]:
import torch

Construct a $5\times 3$ matrix, uninitialized


In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a randomly initialized matrix


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0927, 0.7523, 0.3370],
        [0.2817, 0.7771, 0.9372],
        [0.9265, 0.8119, 0.3911],
        [0.6649, 0.8881, 0.8530],
        [0.7360, 0.7917, 0.2249]])


Get its size


In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.


In [5]:
x[1:3] = 2
print(x)

tensor([[0.0927, 0.7523, 0.3370],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.6649, 0.8881, 0.8530],
        [0.7360, 0.7917, 0.2249]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>

1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)

- fill the entire tensor with 7s

4. Make a torch.ByteTensor of size (5,)

- fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]


In [6]:
norm_tensor = torch.Tensor(2, 17)
# print(norm_tensor)

float_tensor = torch.FloatTensor(3, 1)
# print(float_tensor)

long_tensor = torch.LongTensor(5, 2, 1)
# print(long_tensor)

print(torch.add(long_tensor, 7))

byte_tensor = torch.ByteTensor(5)
index_tensor = torch.tensor([1, 2, 3])
byte_tensor.index_fill_(0, index_tensor, 1)

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])


tensor([0, 1, 1, 1, 0], dtype=torch.uint8)

## 2. Operations

There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1


In [7]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.8178, 1.5843, 0.7552],
        [2.7782, 2.4366, 2.5952],
        [2.8506, 2.1910, 2.0972],
        [1.4730, 1.7007, 1.3147],
        [1.3203, 1.3064, 1.2005]])


### 2.2 Addition: syntax 2


In [8]:
print(torch.add(x, y))

tensor([[0.8178, 1.5843, 0.7552],
        [2.7782, 2.4366, 2.5952],
        [2.8506, 2.1910, 2.0972],
        [1.4730, 1.7007, 1.3147],
        [1.3203, 1.3064, 1.2005]])


### 2.3 Addition: giving an output tensor


In [9]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)

print(result)

tensor([[0.8178, 1.5843, 0.7552],
        [2.7782, 2.4366, 2.5952],
        [2.8506, 2.1910, 2.0972],
        [1.4730, 1.7007, 1.3147],
        [1.3203, 1.3064, 1.2005]])


### 2.4 Addition: in-place

adds `x` to `y`


In [10]:
y.add_(x)
print(y)

tensor([[0.8178, 1.5843, 0.7552],
        [2.7782, 2.4366, 2.5952],
        [2.8506, 2.1910, 2.0972],
        [1.4730, 1.7007, 1.3147],
        [1.3203, 1.3064, 1.2005]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.


You can use standard numpy-like indexing with all bells and whistles!


In [11]:
print(x[:, 1])

tensor([0.7523, 2.0000, 2.0000, 0.8881, 0.7917])


**Read later**: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>


# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)


In [12]:
tensor_product = torch.mul(x, y)
print(tensor_product)

tensor([[0.0758, 1.1918, 0.2545],
        [5.5565, 4.8732, 5.1903],
        [5.7011, 4.3821, 4.1945],
        [0.9794, 1.5104, 1.1214],
        [0.9718, 1.0342, 0.2701]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array


In [13]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [14]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a _view_ of the original tensor, not a copy.


In [15]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically


In [16]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a NumPy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.


In [17]:
# Init. of PyTorch tensor of ones
torch_tensor = torch.ones(5, 2)

# Converting tensor to numpy array
tensor_to_numpy = torch_tensor.numpy()

# Converting numpy array back to tensor
numpy_to_tensor = torch.from_numpy(tensor_to_numpy)

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.


In [18]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.


*Check Google Colab for Part 4 about CUDA tensors*